fix check 'Ebook thumbnailer' on python3
on python 3, mmap.find need bytes-like object, not str. this will give
error:
  File "install.py", line 101, in add_thumbnailer_to_tumbler
    if config_content.find('# Ebook thumbnailer') == -1:
TypeError: a bytes-like object is required, not 'str

Signed-off-by: Dede Dindin Qudsy <xtrymind@gmail.com>